---
title: "VAERS analysis of COVID-19 vaccines"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(readr)
library(magrittr)
library(tidyverse)
library(reshape2)
library(ggplot2)
library(openEBGM)
```

```{r}
X2021VAERSDATA <- read_csv("../data/2021VAERSDATA.csv", 
    col_types = cols(RECVDATE = col_date(format = "%m/%d/%Y"), 
        AGE_YRS = col_skip(), CAGE_MO = col_skip(), 
        RPT_DATE = col_skip(), SYMPTOM_TEXT = col_skip(), 
        DIED = col_skip(), DATEDIED = col_skip(), 
        L_THREAT = col_skip(), ER_VISIT = col_skip(), 
        HOSPITAL = col_skip(), HOSPDAYS = col_skip(), 
        X_STAY = col_skip(), DISABLE = col_skip(), 
        RECOVD = col_skip(), VAX_DATE = col_date(format = "%m/%d/%Y"), 
        ONSET_DATE = col_skip(), NUMDAYS = col_skip(), 
        LAB_DATA = col_skip(), V_ADMINBY = col_skip(), 
        V_FUNDBY = col_skip(), OTHER_MEDS = col_skip(), 
        CUR_ILL = col_skip(), HISTORY = col_skip(), 
        PRIOR_VAX = col_skip(), SPLTTYPE = col_skip(), 
        FORM_VERS = col_skip(), TODAYS_DATE = col_skip(), 
        BIRTH_DEFECT = col_skip(), OFC_VISIT = col_skip(), 
        ER_ED_VISIT = col_skip(), ALLERGIES = col_skip()))

X2021VAERSSYMPTOMS <- read_csv("../data/2021VAERSSYMPTOMS.csv", 
    col_types = cols(SYMPTOMVERSION1 = col_skip(), 
        SYMPTOMVERSION2 = col_skip(), SYMPTOMVERSION3 = col_skip(), 
        SYMPTOMVERSION4 = col_skip(), SYMPTOMVERSION5 = col_skip()))

X2021VAERSVAX <- read_csv("../data/2021VAERSVAX.csv", 
    col_types = cols(VAX_LOT = col_skip()))
```

```{r}
df <- merge(X2021VAERSDATA, X2021VAERSVAX) %>% 
        merge(X2021VAERSSYMPTOMS) %>%
        reshape2::melt(measure.vars=c("SYMPTOM1", "SYMPTOM2", "SYMPTOM3", "SYMPTOM4", "SYMPTOM5")) %>%
        select(-variable)

head(df)
```

# Age stratification

```{r}
df$strat_age <- ifelse(is.na(df$CAGE_YR), "unknown",
                       ifelse(df$CAGE_YR < 25, "under_25",
                              ifelse(df$CAGE_YR < 45, "25-44",
                                     ifelse(df$CAGE_YR < 65, "45-64", "65_plus"))))
```

# Analysis for type of vax

```{r}

processed <- df %>% select(c("VAERS_ID", "VAX_TYPE", "value", "SEX", "strat_age")) %>% set_colnames(c("id", "var1", "var2", "strat_gender", "strat_age")) %>% na.omit() %>% processRaw(stratify = TRUE, max_cats=128)
```

```{r warning=FALSE}
squashed <- processed %>% squashData()
theta_init <- c(alpha1 = 0.2, beta1 = 0.1, alpha2 = 2, beta2 = 4, p = 1/3)
theta_hat <- stats::nlm(negLLsquash, p = theta_init,
           ni = squashed$N, ei = squashed$E, wi = squashed$weight, N_star = 1)$estimate

```

```{r}
qn <- Qn(theta_hat, N = processed$N, E = processed$E)
```

```{r}
processed$ebgm <- ebgm(theta_hat, N = processed$N, E = processed$E, qn  = qn)
```

```{r}
processed$QUANT_05 <- quantBisect(5, theta_hat = theta_hat,
                                  N = processed$N, E = processed$E, qn = qn)
processed$QUANT_95 <- quantBisect(95, theta_hat = theta_hat,
                                  N = processed$N, E = processed$E, qn = qn)
```

# Results by vaccine type

```{r}

processed %>% mutate(type=ifelse(var1=="COVID19","Highlighted","Normal")) %>%
  dplyr::filter(var1 %in% c("COVID19", "DTAP", "FLU4", "FLU3", "MMR", "HPV4", "HPV9")) %>%
  ggplot() +
  geom_boxplot(aes(ebgm, var1, fill=type)) +
  xlab("EBGM value") +
  ylab("Vaccine type") +
  theme(legend.position = "none")
  
ggsave("vs_other_vax.pdf")
```

# Results by COVID-19 vaccine

```{r warning=FALSE}

processed <- df %>% select(c("VAERS_ID", "VAX_NAME", "value", "SEX", "strat_age")) %>% set_colnames(c("id", "var1", "var2", "strat_gender", "strat_age")) %>% na.omit() %>% processRaw(stratify=TRUE, zeroes=FALSE, max_cats=256)
processed <- processed[processed$PRR != Inf, ] 

squashed <- processed %>% squashData()
theta_init <- c(alpha1 = 0.2, beta1 = 0.1, alpha2 = 2, beta2 = 4, p = 1/3)
theta_hat <- stats::nlm(negLLsquash, p = theta_init,
           ni = squashed$N, ei = squashed$E, wi = squashed$weight, N_star = 1)$estimate

qn <- Qn(theta_hat, N = processed$N, E = processed$E)

processed$ebgm <- ebgm(theta_hat, N = processed$N, E = processed$E, qn  = qn)

processed$QUANT_05 <- quantBisect(5, theta_hat = theta_hat,
                                  N = processed$N, E = processed$E, qn = qn)
processed$QUANT_95 <- quantBisect(95, theta_hat = theta_hat,
                                  N = processed$N, E = processed$E, qn = qn)
```

```{r}

processed %>% 
  dplyr::filter(var1 %in% c(c("COVID19 (COVID19 (JANSSEN))", "COVID19 (COVID19 (MODERNA))", "COVID19 (COVID19 (PFIZER-BIONTECH))"))) %>%
  ggplot() +
  geom_boxplot(aes(ebgm, var1)) +
  xlab("EBGM value") +
  ylab("Vaccine type") + 
  xlim(c(0, 5.0))

ggsave("covid_vax.pdf")
```
